version: "3.8"

services:
  backend:
    image: platform-backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/platform
      - GO_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform
    ports:
      - "5432:5432"